### ISSUE TITLE
Installation error in Windows 10

### ISSUE THREAD

**Issue by tellts** [zlatnaspirala/cross-k#2]
Hello. Could you place on the Internet a ready-made Docker image with all the stuffing installed, if transferring from computer to computer is possible in principle? Because I couldn't install it myself.
Or I ask you to advise how you can solve the problem.

I recorded the video showing problems when running a bat file.
https://youtu.be/8MqFPGLFX1Y

In the log file below, at first I did not enter the command in the right place:
kivy_venv\Scripts\activate
But then I fixed it.

`C:\Users\admin>docker -v
Docker version 20.10.14, build a224086

C:\Users\admin>python -m pip install --upgrade --force-reinstall pip
Collecting pip
  Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.0.4

C:\Users\admin>python -m pip install --upgrade pip setuptools virtualenv
Requirement already satisfied: pip in c:\python39\lib\site-packages (22.0.4)
Requirement already satisfied: setuptools in c:\python39\lib\site-packages (56.0.0)
Collecting setuptools
  Downloading setuptools-62.1.0-py3-none-any.whl (1.1 MB)
     ---------------------------------------- 1.1/1.1 MB 2.2 MB/s eta 0:00:00
Requirement already satisfied: virtualenv in c:\python39\lib\site-packages (20.13.0)
Collecting virtualenv
  Downloading virtualenv-20.14.1-py2.py3-none-any.whl (8.8 MB)
     ---------------------------------------- 8.8/8.8 MB 6.9 MB/s eta 0:00:00
Requirement already satisfied: platformdirs<3,>=2 in c:\python39\lib\site-packages (from virtualenv) (2.4.1)
Requirement already satisfied: filelock<4,>=3.2 in c:\python39\lib\site-packages (from virtualenv) (3.4.2)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\python39\lib\site-packages (from virtualenv) (0.3.4)
Requirement already satisfied: six<2,>=1.9.0 in c:\python39\lib\site-packages (from virtualenv) (1.16.0)
Installing collected packages: virtualenv, setuptools
  Attempting uninstall: virtualenv
    Found existing installation: virtualenv 20.13.0
    Uninstalling virtualenv-20.13.0:
      Successfully uninstalled virtualenv-20.13.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 56.0.0
    Uninstalling setuptools-56.0.0:
      Successfully uninstalled setuptools-56.0.0
Successfully installed setuptools-62.1.0 virtualenv-20.14.1

C:\Users\admin>python -m virtualenv kivy_venv
created virtual environment CPython3.9.5.final.0-64 in 9487ms
  creator CPython3Windows(dest=C:\Users\admin\kivy_venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\admin\AppData\Local\pypa\virtualenv)
    added seed packages: pip==21.3.1, setuptools==60.5.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

C:\Users\admin>python crossk.editor
python: can't open file 'C:\Users\admin\crossk.editor': [Errno 2] No such file or directory

C:\Users\admin>kivy_venv\Scripts\activate

(kivy_venv) C:\Users\admin>python crossk.editor
C:\python39\python.exe: can't open file 'C:\Users\admin\crossk.editor': [Errno 2] No such file or directory

(kivy_venv) C:\Users\admin>`

**Comment by zlatnaspirala** [comment]
Welcome @tellts ! 

  Do you have `crossk.editor` at the 'C:\Users\admin\`
  
  If file exist maybe you can rename it something like `crossk.py`

**Comment by tellts** [comment]
I opened this folder and this file was not in this folder. In addition, I searched all over the computer where it could be installed using the Everything program and did not find it.

**Comment by zlatnaspirala** [comment]
You need to open terminal and navigate to the root folder from yt video it is `c:\\a1\` .
Now you can run: `python crossk.editor`

If still something's wrong with kivy running take a look for help at : https://kivy.org/doc/stable/installation/installation-windows.html

**Comment by tellts** [comment]
I removed the existing docker container for now. Therefore, for the time being I can not take your advice until I install everything on a new one. At the same time, I have Linux installed on another hard drive and there is Bulldozer and Kivy. Is it possible to run your development there without installing a Docker container?

**Comment by zlatnaspirala** [comment]
Now i catch , 
 i made docker just for android build package, you don't need linux or docker if you wanna run crossk editor.
 just use classic git clone this project, install kivy 2 and run it.

This project is writen on windows 10.

From root folder:
```
 kivy_venv\Scripts\activate
 python crossk.editor
```


This is link for android build from windows with docker: 
https://hub.docker.com/repository/docker/zlatnaspirala/crossk-pack

**Comment by tellts** [comment]
Thanks to. I just found 3 command line commands on the page at the link and I don’t understand which ones to enter? Should this be entered? docker pull zlatnaspirala/crossk-pack
I don’t understand, do I need to somehow download the container first and then enter commands into the console or will the commands download the container themselves?

**Comment by zlatnaspirala** [comment]
Before all i use docker only when i wanna build android package.


You need to learn basics for docker, install it for windows [ use GUI ] [ download , install and run]  and try in you terminal : 
`docker --version` if everything is ok you docker cmd is ready.

First pull image , when you run image and you got container:

This is list of all downloaded [pulled] images:
```
docker image list
```

CHANGE THIS  
YOURPATH_TO_CROSSK_PROJECT   =      c:\a1\

docker run -a stdin -a stdout -i -t -v YOURPATH_TO_CROSSK_PROJECT:/home/user/crossk --workdir /home/user/crossk zlatnaspirala/crossk-pack:beta buildozer -v android debug"

```
docker run -a stdin -a stdout -i -t -v c:\\a1\:/home/user/crossk --workdir /home/user/crossk zlatnaspirala/crossk-pack:beta buildozer -v android debug"
```

This is list of all active containers:

```
docker container list
```

Enter intro container bash (if needed):
```
  docker exec -it 0171c0dce7f0SOME_ID bash
```

Copy somefile intro container and create new image.
```
docker cp /var/applications/somefile.txt c6f4b9a84045:/var/applications/somefile.txt
```

Copy from docket to you computer
cp c6f4b9a84045:/etc/kurento/kurento.conf.json /var/applications/kurento-project/kurento.conf.json

After all create new image:

  docker commit c6f4b9a84045 yuo_new-updated-image-2:0.0.1

**Comment by tellts** [comment]
Look please. There might be something wrong at the end of the log.
`C:\Users\admin>docker --version
Docker version 20.10.14, build a224086

C:\Users\admin>docker image list
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

C:\Users\admin>docker run -a stdin -a stdout -i -t -v c:\\a1\:/home/user/crossk --workdir /home/user/crossk zlatnaspirala/crossk-pack:beta buildozer -v android debug"
Unable to find image 'zlatnaspirala/crossk-pack:beta' locally
beta: Pulling from zlatnaspirala/crossk-pack
5d3b2c2d21bb: Pull complete
3fc2062ea667: Pull complete
75adf526d75b: Pull complete
4fee125c05b8: Pull complete
883e7b1b4305: Pull complete
18d9bf3087f0: Pull complete
e26d2d293316: Pull complete
437fc36620ee: Pull complete
1cc441e96095: Pull complete
dbabf016bef5: Pull complete
f3fcdf383d76: Pull complete
69e5727168b3: Pull complete
e6ed4ff1df5f: Pull complete
c754603b2f12: Pull complete
e92caa3b4d42: Pull complete
cb883d771534: Pull complete
f4dc9a4dec13: Pull complete
3af1f6b52bca: Pull complete
21979eaa511a: Pull complete
Digest: sha256:10ed94e45c57fe98a0ba64a837a2d730eea44c11dac53b97f11f43b0e52baebf
Status: Downloaded newer image for zlatnaspirala/crossk-pack:beta
# Ensure build layout
No buildozer.spec found in the current directory. Abandon.

C:\Users\admin>docker container list
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

C:\Users\admin>  docker exec -it 0171c0dce7f0SOME_ID bash
Error: No such container: 0171c0dce7f0SOME_ID

C:\Users\admin>`
